export const BookingStatus = {
	PENDING: "PENDING",
	CONFIRMED: "CONFIRMED",
	COMPLETED: "COMPLETED",
	CANCELLED_BY_USER: "CANCELLED_BY_USER",
	CANCELLED_BY_MENTOR: "CANCELLED_BY_MENTOR",
} as const;

export const SlotStatus = {
	AVAILABLE: "AVAILABLE",
	BOOKED: "BOOKED",
	UNAVAILABLE: "UNAVAILABLE",
} as const;
